### ISSUE TITLE
Enhancement: when processing a listfile, save each input audio as separate output file

### ISSUE THREAD

**Issue by renaissanceGeek** [cobaltspeech/cubic-cli#15]
Right now, we can only submit one `--outputfile` to save to, so when we're processing multiple files, all the transcripts end up in the same file.  It would be nice to be able to specify `--dir` and have the cli create a new file for each audio file in the listfile, named according to the specified id.  E.g., the following listfile
```
foo  /mnt/audio/recordings/foo.wav
bar  /mnt/audio/recordings/somethingElse.mp3
baz  /mnt/audio/recordings/
```
Would create 3 files in the specified directory foo.txt, bar.txt, baz.txt.  Then the json output wouldn't need to contain the id.

If no dir is specified, would write to stdout like now.

**Comment by jhollowayj** [comment]
Does #19 solve all of this issue @renaissanceGeek ?

**Comment by renaissanceGeek** [comment]
Yes--thanks very much!
