### ISSUE TITLE
Multiple output formats

### ISSUE THREAD

**Issue by renaissanceGeek** [cobaltspeech/cubic-cli#4]
From @rslish 

I'd like to have a flag that configures the kind of output we get. We could have 3 options (maybe more):
1 - Just the 1-best transcript
2 - The full result as an unformatted JSON blob
3 - The full JSON result prettified

The default would be 1. That's typically what we want when we're evaluating a model. 2 would be useful when we need the full result and have to do some additional processing on the cnet because each line would be one result. 3 is useful when we're manually inspecting results.

**Comment by happyalu** [comment]
@stansalvador and I had also discussed this; I think the summary was:

```
// --otype plain:

utt_id <tab> result1.Alternatives[0].Transcript
utt_id <tab> result2.Alternatives[0].Transcript
utt_id <tab> result3.Alternatives[0].Transcript
```

```
// --otype nbest:
utt_id <tab> result1.Alternatives with word level timestamps and confidences
utt_id <tab> result2.Alternatives
utt_id <tab> result3.Alternatives
```

```
// --otype cnet:

utt_id <tab> result1.Cnet
utt_id <tab> result2.Cnet
utt_id <tab> result3.Cnet
```

We could have a `[--output-prettify]` flag; but I'm not sure how one could prettify json that is in the second column of a tsv format.

**Comment by renaissanceGeek** [comment]
Maybe --output-prettify only applies if it's processing a single file?  But probably lower priority than the other formats

**Comment by jhollowayj** [comment]
Why does `nbest` only include the `word level timestamps and confidences` on `result1` and not the others?  Is there that much of a burden to include it with the rest of them?
